language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"

matrix:
  allow_failures:
    - python: "3.5"  # TODO: Investigate why language detection act differently
    - python: "3.10-dev"

install:
  - pip install nose codecov
  - python setup.py install

script:
  - "nosetests --with-coverage --cover-package=charset_normalizer test/*.py"

after_success:
  - codecov
